services:
  porthole:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    container_name: porthole-test
    ports:
      - "9753:9753"
      - "5005:5005"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

