server:
  port: 9753
  shutdown: graceful
  compression:
    enabled: true
    mime-types: application/json,text/html,text/plain
    min-response-size: 1024

spring:
  application:
    name: porthole
    version: "@project.version@"
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 20s
  banner.location: classpath:/banner.txt

# Docker configuration
porthole:
  docker:
    host: unix:///var/run/docker.sock
    connection-timeout: 5s
    response-timeout: 60s

# Icon configuration
dashboard:
  icons:
    path: /app/config/icons.yml
    url: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp
    extension: .webp

# Registry configuration
registry:
  timeout:
    connect: 5s
    read: 10s
  cache:
    ttl: 1h
    version-max-size: 100
  urls:
    registry: "https://registry-1.docker.io/v2/"
    auth: "https://auth.docker.io/token?service=registry.docker.io&scope=repository:"
    repositories: "https://hub.docker.com/v2/repositories/"

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      show-components: always
